# Generated by Django 5.0.1 on 2026-01-24 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='lot_number',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='inventoryitem',
            unique_together={('lot_number', 'fabric_type')},
        ),
    ]
