# Generated by Django 5.0.1 on 2026-01-25 13:32

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('category', models.CharField(choices=[('Office Rent', 'Office Rent'), ('Employees Salary', 'Employees Salary'), ('Builty (Transport)', 'Builty (Transport)'), ('Packing', 'Packing'), ('Electricity Bill', 'Electricity Bill'), ('Gas Bill', 'Gas Bill'), ('Water Bill', 'Water Bill'), ('Internet Bill', 'Internet Bill'), ('Other Expenses', 'Other Expenses')], max_length=50)),
                ('description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('payment_method', models.CharField(choices=[('Cash', 'Cash'), ('Bank', 'Bank'), ('Credit', 'Credit')], default='Cash', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'expenses',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
