# Generated by Django 5.0.1 on 2026-02-15 11:40

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='commission_settled',
        ),
        migrations.AddField(
            model_name='invoice',
            name='commission_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.CreateModel(
            name='CommissionPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('method', models.CharField(choices=[('Cash', 'Cash'), ('Bank', 'Bank')], default='Cash', max_length=20)),
                ('bank_name', models.CharField(blank=True, max_length=255, null=True)),
                ('tid', models.CharField(blank=True, help_text='Transaction ID', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commission_payments', to='transactions.invoice')),
            ],
            options={
                'db_table': 'commission_payments',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
